namespace Microsoft.AspNetCore.Cryptography.Cng
{
	internal enum BCryptKeyDerivationBufferType
	{
		KDF_HASH_ALGORITHM,
		KDF_SECRET_PREPEND,
		KDF_SECRET_APPEND,
		KDF_HMAC_KEY,
		KDF_TLS_PRF_LABEL,
		KDF_TLS_PRF_SEED,
		KDF_SECRET_HANDLE,
		KDF_TLS_PRF_PROTOCOL,
		KDF_ALGORITHMID,
		KDF_PARTYUINFO,
		KDF_PARTYVINFO,
		KDF_SUPPPUBINFO,
		KDF_SUPPPRIVINFO,
		KDF_LABEL,
		KDF_CONTEXT,
		KDF_SALT,
		KDF_ITERATION_COUNT
	}
}
