namespace Microsoft.AspNetCore.Components.RenderTree
{
	/// <summary>
	/// Types in the Microsoft.AspNetCore.Components.RenderTree are not recommended for use outside
	/// of the Blazor framework. These types will change in future release.
	/// </summary>
	public enum RenderTreeFrameType : short
	{
		/// <summary>
		/// Used only for uninitialized frames.
		/// </summary>
		None,
		/// <summary>
		/// Represents a container for other frames.
		/// </summary>
		Element,
		/// <summary>
		/// Represents text content.
		/// </summary>
		Text,
		/// <summary>
		/// Represents a key-value pair associated with another <see cref="T:Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame" />.
		/// </summary>
		Attribute,
		/// <summary>
		/// Represents a child component.
		/// </summary>
		Component,
		/// <summary>
		/// Defines the boundary around range of sibling frames that should be treated as an
		/// unsplittable group for the purposes of diffing. This is typically used when appending
		/// a tree fragment generated by external code, because the sequence numbers in that tree
		/// fragment are not comparable to sequence numbers outside it.
		/// </summary>
		Region,
		/// <summary>
		/// Represents an instruction to capture or update a reference to the parent element.
		/// </summary>
		ElementReferenceCapture,
		/// <summary>
		/// Represents an instruction to capture or update a reference to the parent component.
		/// </summary>
		ComponentReferenceCapture,
		/// <summary>
		/// Represents a block of markup content.
		/// </summary>
		Markup
	}
}
